# Project information
site_name: J/L2 Docs
site_url: https://xeman.github.io/l2docs/
nav: 
  - Home: index.md
  - DNS (Domain Name System): dns.md
  - WordPress: wordpress.md
  - Magento: magento.md
  - Premium Business Email: pbe.md
  - CloudSites: cloudsites.md
  - .bashrc: bashrc.md
  - Ports: ports.md
# Theme
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
  palette:
    scheme: slate
    primary: lime
    
  font:
      text: Robot
      code: Roboto Mono

# Plugins      
plugins:
    - search 
    - offline 
    - encryptcontent:
        title_prefix: ''
        search_index: 'clear'
        global_password: 'lozinka1'
    

